package res

const PRESIDENT_TIME  = 1500
const PRESIDENT_DELTA  = 500

const TASK_LIST_LENGTH = 500
const SHOP_ITEM_COUNT = 500

const WORKERS = 4
const WORKER_TIME = 750
const WORKER_REST_TIME  = 3000
const WORKER_DELTA = 2000
const WORKER_DELTA_DELTA  = 2000

const CUSTOMERS = 2
const SHOPPING_TIME = 17000
const SHOPPING_TIME_DELTA  =  3000
const MAX_ITEMS_PER_BUY  = 3

const MULTIPLICATION_MACHINES = 3
const MULTIPLICATION_MACHINES_TIME = 750
const ADD_MACHINES = 3
const ADD_MACHINES_TIME = 650

const SERVICE_WORKERS = 2
const TIME_TO_FIX = 2000
const CHANCE_OF_BREAKAGE = 10